
const companies = [
  "billaw.png",
  "bilogos.png",
  "boldtell.png",
  "boocant.png",
  "bujnews.png",
  "eret.png",
  "fan.png",
  "foundersschool.png",
  "frendal.png",
  "frontlett.png",
  "hostwll.png",
  "knowtiped.png",
  "knowtixed.png",
  "kofoundme.png",
  "kreeca.png",
  "krowdback.png",
  "kureen.png",
  "mannyimages.png",
  "meezor.png",
  "muse.png",
  "ontecx.png",
  "otunna.png",
  "perfaid.png",
  "qeeki.png",
  "rakayar.png",
  "recurl.png",
  "reentty.png",
  "rekruit.png",
  "remanno.png",
  "sbo.png",
  "simpext.png",
  "skimake.png",
  "ssmarket.png",
  "stuwok.png",
  "triftpay.png",
  "wanodu.png",
  "wettaa.png",
  "zebulon.png",
  "zinr.png"
]

module.exports = { companies }